sudo: required
service:
  - docker
before_install:
  - docker build -t palaniec:mongodb:latest .
script:
  - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
  - docker images
  - docker push palaniec:mongodb:latest
notification:
  email:
    recipients:
      - kpalani.ec@gmail.com
    on_success: always
    on_failure: always
